title: "SmartOps Solutions Site"
description: "A secure page powered by Jekyll"
baseurl: "" # the subpath of your site, leave empty for root
url: "https://SmartOps-Solutions.github.io" # the base hostname & protocol for your site
markdown: kramdown
theme: minima # Default theme, you can change this to any supported theme

# Build settings
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle
  - vendor/cache
  - vendor/gems
  - vendor/ruby
