name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository content
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        run: |
          git clone https://$GITHUB_ACTOR:$GITHUB_TOKEN@github.com/SmartOps-Solutions/github.io.git .
          git fetch
          git checkout $GITHUB_SHA

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0

      - name: Install Jekyll and Bundler
        run: |
          gem install bundler
          bundle install

      - name: Fetch secrets and build site
        env:
          INDEX_URL: ${{ secrets.URL }}
        run: |
          echo "Secret URL: $INDEX_URL"
          echo "<!DOCTYPE html><html><head><title>Secure Page</title></head><body><h1>Welcome to Our Secure Page</h1><p>Secret URL: $INDEX_URL</p></body></html>" > index.html
          bundle exec jekyll build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.TOKEN }}
          publish_dir: ./_site
